### PR TITLE
#9: Reduce messages if number ist higher than SQS can handle

### LINKED ISSUE #9: MaxNumberOfMessages too high
Hi,

as described [here](https://github.com/lizards-and-pumpkins/catalog/blob/068b60aeb0875aef49aa79d02230a315cfefcc91/src/Messaging/Command/CommandConsumer.php#L15), the default maximum of messages to process is 200.

For SQS the MaxNumberOfMessages is 10. When I try to consume the commands following error is thrown:
```
Value 200 for parameter MaxNumberOfMessages is invalid. Reason: Must be between 1 and 10, if provided.  LizardsAndPumpkins\Messaging\Command\FailedToReadFromCommandQueueMessage  File: /var/www/html/vendor/aws/aws-sdk-php/src/Aws/Common/Exception/NamespaceExceptionFactory.php:91
```

The limit is documented [here](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-limits.html).

> A single message batch request can include a maximum of 10 messages. For more information, see Configuring AmazonSQSBufferedAsyncClient in the Amazon SQS Batch Actions section.

The limit should be automatically adjusted to SQS.

Thanks :)

### PR DESCRIPTION
**Pull request by Schrank**
I'm not sure it is a good idea to just™ reduce the number of messages. But at this point the alternative would be to throw an exception.

The biggest problem I see is, if you expect 200 messages and don't check count() but instead if you get less then 200 stop processing. But I don't see how to handle this problem in a good way.

Happy about your feedback as well Marlon!

Closes #9

### CODE REVIEW

**Comment by LlZARD** [comment]
The first idea that came to my mind is why not move number of messages to consume from `QueueMessageConsumer`s to `Queue`s?

File: src/SqsQueue.php [hunk 1]
```diff
@@ -13,6 +13,7 @@
 
 class SqsQueue implements Queue, Clearable
 {
+    const MAX_AWS_SQS_CONSUMEABLE = 10;
```
Comment (LlZARD) [inline src/SqsQueue.php]: Please add a newline below.

File: tests/Integration/Suites/LizardsAndPumpkins/Messaging/Queue/Sqs/QueueAwsTest.php [hunk 2]
```diff
@@ -93,6 +93,35 @@ public function receive(Message $message): void
         $this->assertSame($message->serialize(), $returnedMessage->serialize());
     }
 
+    public function testMoreThan20MessagesComeBack()
```
Comment (LlZARD) [inline tests/Integration/Suites/LizardsAndPumpkins/Messaging/Queue/Sqs/QueueAwsTest.php]: 20?
